[build]
  publish = "build/client"
  command = "npm run build"

# For SSR - this is CRITICAL for React Router v7 SSR
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200

# For API functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Cache assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
