[build]
  publish = "build/client"
  command = "npm run build"

# Critical: This handles client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# For SSR functions (if using)
[functions]
  directory = "netlify/functions"

# Cache assets for better performance  
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
