[build]
  publish = "dist/client"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# For SSR functions (if using React Router v7 SSR)
[functions]
  directory = "netlify/functions"
