[build]
  publish = "build/client"  # Changed from dist/client to build/client
  command = "npm run build"

# Remove or fix the problematic redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# For SSR functions
[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
