[build]
  publish = "dist/client"
  command = "npm run build"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# For SSR functions (if using React Router v7 SSR)
[functions]
  directory = "netlify/functions"
